-- Auto-generated by HyDE // Read-only
local ui_state = {
    ui = {
        hyde_theme = "Catppuccin Mocha",
        -- gtk
        gtk_theme = "Catppuccin-Mocha",
        icon_theme = "Tela-circle-dracula",
        color_scheme = "prefer-dark",

        -- Cursor
        cursor_theme = "",
        cursor_size = nil,

        -- Fonts
        font = "",
        font_size = nil,
        document_font = "",
        document_font_size = nil,
        monospace_font = "",
        monospace_font_size = nil,
        notification_font = "",
        bar_font = "",
        menu_font = "",

        -- Extra Themes
        code_theme = "Wallbash",
        sddm_theme = "",
    },
    wallbash = {
        mode = "theme",
    },
}

return ui_state

