# Virtual Hosts
#
# Required modules: mod_log_config

# If you want to maintain multiple domains/hostnames on your
# machine you can setup VirtualHost containers for them. Most configurations
# use only name-based virtual hosts so the server doesn't need to worry about
# IP addresses. This is indicated by the asterisks in the directives below.
#
# Please see the documentation at 
# <URL:http://httpd.apache.org/docs/2.4/vhosts/>
# for further details before you try to setup virtual hosts.
#
# You may use the command line option '-S' to verify your virtual host
# configuration.

#
# VirtualHost example:
# Almost any Apache directive may go into a VirtualHost container.
# The first VirtualHost section is used for all requests that do not
# match a ServerName or ServerAlias in any <VirtualHost> block.
#

# DEFAULT localhost
<VirtualHost *:80>
    ServerName localhost
    DocumentRoot "/srv/http"

    <Directory "/srv/http">
        AllowOverride All
        Require all granted
    </Directory>
</VirtualHost>

# WORDPRESS ELEMENTOR
<VirtualHost *:80>
    ServerName elementor.local
    DocumentRoot "/srv/http/wordpress/elementor"

    <Directory "/srv/http/wordpress/elementor">
        AllowOverride All
        Require all granted
    </Directory>

    ErrorLog "/var/log/httpd/elementor_error.log"
    CustomLog "/var/log/httpd/elementor_access.log" combined
</VirtualHost>

# WORDPRESS Porto
<VirtualHost *:80>
    ServerName porto.local
    DocumentRoot "/srv/http/wordpress/porto"

    <Directory "/srv/http/wordpress/porto">
        AllowOverride All
        Require all granted
    </Directory>

    ErrorLog "/var/log/httpd/porto_error.log"
    CustomLog "/var/log/httpd/porto_access.log" combined
</VirtualHost>

# WORDPRESS Website
<VirtualHost *:80>
    ServerName website.local
    DocumentRoot "/srv/http/wordpress/website"

    <Directory "/srv/http/wordpress/website">
        AllowOverride All
        Require all granted
    </Directory>

    ErrorLog "/var/log/httpd/website_error.log"
    CustomLog "/var/log/httpd/website_access.log" combined
</VirtualHost>

# WORDPRESS Blogv2
<VirtualHost *:80> 
    ServerName blog2.local
    DocumentRoot "/srv/http/wordpress/blog2"

    <Directory "/srv/http/wordpress/blog2">
        AllowOverride All  
        Require all granted
    </Directory>

    ErrorLog "/var/log/httpd/blog2_error.log"
    CustomLog "/var/log/httpd/blog2_access.log" combined
</VirtualHost>

# WORDPRESS gatahu
<VirtualHost *:80> 
    ServerName gatahu.local
    DocumentRoot "/srv/http/wordpress/gatahu"

    <Directory "/srv/http/wordpress/gatahu">
        AllowOverride All  
        Require all granted
    </Directory>

    ErrorLog "/var/log/httpd/gatahu_error.log"
    CustomLog "/var/log/httpd/gatahu_access.log" combined
</VirtualHost>
